# Generated by Django 4.1.5 on 2023-02-04 12:04

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[company.models.validate_deadline]),
        ),
    ]
